<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../RxFlow.Domain/RxFlow.Domain.csproj"/><ProjectReference Include="../RxFlow.Infrastructure/RxFlow.Infrastructure.csproj"/></ItemGroup><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App"/><PackageReference Include="Hangfire.AspNetCore"/><PackageReference Include="Confluent.Kafka"/><PackageReference Include="Newtonsoft.Json"/></ItemGroup></Project>
