<Project Sdk="Microsoft.NET.Sdk.Web"><ItemGroup><ProjectReference Include="../RxFlow.Application/RxFlow.Application.csproj"/><ProjectReference Include="../RxFlow.Infrastructure/RxFlow.Infrastructure.csproj"/><ProjectReference Include="../RxFlow.Workers/RxFlow.Workers.csproj"/></ItemGroup><ItemGroup><PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/><PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all"/><PackageReference Include="Hangfire.AspNetCore"/><PackageReference Include="Hangfire.PostgreSql"/><PackageReference Include="OpenTelemetry.Extensions.Hosting"/><PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol"/><PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore"/><PackageReference Include="OpenTelemetry.Instrumentation.Http"/><PackageReference Include="Newtonsoft.Json"/></ItemGroup></Project>
