<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="../../src/RxFlow.Application/RxFlow.Application.csproj"/><ProjectReference Include="../../src/RxFlow.Infrastructure/RxFlow.Infrastructure.csproj"/><ProjectReference Include="../../src/RxFlow.Workers/RxFlow.Workers.csproj"/></ItemGroup><ItemGroup><PackageReference Include="Microsoft.NET.Test.Sdk"/><PackageReference Include="xunit"/><PackageReference Include="xunit.runner.visualstudio"/><PackageReference Include="FluentAssertions"/><PackageReference Include="NSubstitute"/><PackageReference Include="FsCheck.Xunit"/><PackageReference Include="Testcontainers.PostgreSql"/><PackageReference Include="SSH.NET"/></ItemGroup></Project>
